### ISSUE TITLE
Add support for self-hosted ClojureScript?

### ISSUE THREAD

**Issue by metametadata** [jeaye/orchestra#10]
Just an idea: library should work in [Lumo](https://github.com/anmonteiro/lumo) and [Planck](https://github.com/mfikes/planck). I would definitely benefit by validating `:ret` specs in my Lumo scripts.

Current behaviour in Lumo:

```
ᐅ lumo -c "$(./classpath.sh)" 
Lumo 1.8.0-beta
ClojureScript 1.9.927
Node.js v8.5.0
 Docs: (doc function-name-here)
       (find-doc "part-of-name-here")
 Source: (source function-name-here)
 Exit: Control+D or :cljs/quit or exit

cljs.user=> (require '[orchestra-cljs.spec.test :as st])
                                              ⬆
WARNING: Use of undeclared Var orchestra-cljs.spec.test$macros/eval at line 112 orchestra_cljs/spec/test.cljc
                                              ⬆
WARNING: Use of undeclared Var orchestra-cljs.spec.test$macros/eval at line 135 orchestra_cljs/spec/test.cljc
nil
```

**Comment by jeaye** [comment]
Hey @metametadata, thanks for the ticket. I don't think this would be possible, due to how clojure.spec is implemented for ClojureScript. It depends on macros, where each instrumented var is stored in an atom, in the Clojure world, during macro expansion. `instrument` itself is just implemented as a macro which operates on that state to generate the necessary ClojureScript code.

With that said, I don't discount that all of this *could*, in some way, work in a purely ClojureScript environment, it would require a rewrite of clojure.spec. The goal of Orchestra is to stay as close as possible to upstream clojure.spec and just add the instrumentation of `:ret` and `:fn` specs for functions. I think the best place to handle this self-hosting support would be in ClojureScript's clojure.spec JIRA. If the changes were made there, they would be propogated into Orchestra as well.

Feel free to discuss here, in case I've misunderstood, but I'm closing this for now.

**Comment by metametadata** [comment]
Thank you for the reply. I think I don't yet understand all the intricacies but hope it should be doable since `core.spec` currently works in Lumo and as @anmonteiro [noted](https://clojurians-log.clojureverse.org/lumo/2017-08-10.html#inst-2017-08-10T19:29:07.665274Z): "we put a lot of effort making spec self-host compatible".

**Comment by jeaye** [comment]
Ok, I may not fully understand the issue then. Please let me know this:

* Does clojure.spec work in lumo for you?

If clojure.spec works in lumo and Orchestra doesn't, that's a bug in Orchestra. If clojure.spec doesn't work in lumo, then Orchestra wouldn't be expected to either.

**Comment by anmonteiro** [comment]
Spec does work in Lumo, but `cljs.spec.test.alpha` is somewhat of a hairy one because of `eval`.

We treat this explicitly in Lumo by monkey-patching `eval` in the `cljs.spec.test.alpha` namespace: https://github.com/anmonteiro/lumo/blob/master/src/cljs/snapshot/lumo/repl.cljs#L231-L232

**Comment by metametadata** [comment]
> Does clojure.spec instrumentation work in lumo for you?
That's correct.

**Comment by jeaye** [comment]
Thanks for weighing in, @anmonteiro. @metametadata it looks like instrumentation only works in Lumo due to this monkey patching. For those interested in full instrumentation, it may be good to add Orchestra to that monkey patching as well.

Does that sound like something Lumo would like to support, @anmonteiro?

**Comment by anmonteiro** [comment]
Adding ad-hoc monkey-patching support for certain libraries is out of the question. IMHO we should come up with a general solution

**Comment by anmonteiro** [comment]
i.e. if libraries need eval in macros and want to support self-hosted ClojureScript they can conditionally call `lumo.core/eval` instead of `clojure.core/eval`

**Comment by jeaye** [comment]
Yeah, I can totally understand that; the more monkey patching, the worse things are to maintain. 

Unfortunately, it looks like it's either Lumo or Orchestra which needs to be patched to specifically look for the other's existence. I'm hesitant to move Orchestra any further from upstream clojure.spec than is necessary for providing complete instrumentation, just as you're hesitant to add another ns to the patching.

Do you see any other solution?

**Comment by metametadata** [comment]
What about updating Lumo/Planck to make `eval` available during compilation without requiring `lumo.core`? Would be convenient for library authors targeting multiple platforms (i.e. Clojure/CLJS/Lumo/Planck).

I actually already had this problem in my project where code targets Clojure and Lumo. Had to do this:

```clj
(defn -eval
  "Platform agnostic eval."
  [form]
  #?(:cljs (lumo-core/eval form)
     :clj  (eval form)))
```

**Comment by jeaye** [comment]
That sounds like a solution that would address not only this issue, but also any similar issues with other projects. At what cost though? Would making `eval` available globally in Lumo negatively affect anyone?

**Comment by metametadata** [comment]
Politely pinging @anmonteiro regarding the proposal to make `eval` globally available.

**Comment by metametadata** [comment]
I'm still interested to see this working in Lumo. Can we reopen the issue? 

What was needed to make Orchestra work in Lumo? Looking at it again, I'm not sure that Lumo patching `eval` in `cljs.spec.test.alpha$macros` is somehow a blocker for Orchestra.

**Comment by arichiardi** [comment]
The latest ClojureScript exposes [`eval`]( https://github.com/clojure/clojurescript/blob/master/src/main/cljs/cljs/core.cljs#L11520) so probably we could leverage that.

I have a PR in progress for lumo https://github.com/anmonteiro/lumo/commit/f29d4406c2cb9dda5fc0ce42d68dce68e8ba04bb

Basically there is not much to do there, just let cljs use eval provided by lumo in the context of evaluating a form.

**Comment by jeaye** [comment]
@metametadata Lumo has some specific patching for clojure.spec.test to get it working. Orchestra is just a fork of clojure.spec.test with some minor changes to the instrumentation, with with different `ns` naming. So, if nothing changed, Lumo would need to do the same patching to support Orchestra.

I think that @arichiardi's PR might make it so that Lumo accepts Orchestra (and many other libraries) without any further changes. If my understanding is correct, we should put our efforts into making sure that gets merged.
