### ISSUE TITLE
defn spec macro?

### ISSUE THREAD

**Issue by didibus** [jeaye/orchestra#12]
On the Clojure mailing list, it was suggested that Orchestra was potentially working on adding a macro to replace def and defn, which would allow to define inline specs as the function/var is defined. Is this still on the roadmap?

**Comment by jeaye** [comment]
You're quite right, @didibus. Thanks for the reminder. Currently, we're using the bellow form for an alternative `defn`.

```clojure
   ; Example usage
   (defn-spec str->kw keyword?
     [s ::spec.util/non-blank]
      (keyword s))

   ; Multiple arities are also supported
   (defn-spec inc' number?
     ([a number?]
      (inc' a 1))
     ([a number?, n number?]
      (+ a n)))
```

Others I've seen have gone for a `sym :- spec` syntax, but that implies that specs are optional. That doesn't fly with Orchestra's opinions on spec'ing, so `any?` should be used anywhere specs aren't otherwise provided.

We're currently using this, to great effect, but I haven't yet brought it into Orchestra. As for a timeline on this, I'll get it merged in tonight, with some tests and docs over the weekend.

I'm not sure about a solution for `def` though; that never ocurred to me. Do you have a suggestion for how that'd work?

**Comment by didibus** [comment]
I prefer that syntax to using :- as mentioned. I think if you don't want to spec everything, normal defn can do. And any? is always an option as you said.

Is there a place in the syntax for the fn spec? Like maybe after the arg list?

I guess I mentioned def without also really thinking about it. I guess something like this could maybe be useful:

(def-spec symbol-name <doc-string> <spec> value)
Where it would create a ::symbol-name keyword with spec.

My thinking is that on the def-spec evaluation, it could use set-validator! to set the spec as the validator for the var, and also validate the initial value. If the value is another reference type, it could also set-validator! the spec on it and validate initial value.

It would also now allow you to defn-spec a method and say it took [a ::symbol-name] as an argument. 

Not sure about the def-spec idea though. Especially the smart part with reference types, could get confusing as to what you are speccing.

**Comment by jeaye** [comment]
> Is there a place in the syntax for the fn spec? Like maybe after the arg list?

Clojure has built-in support for the meta map for functions, so `defn-spec` just rides on that. I have the macro merged and some tests pushed. You can see the full boat here: https://github.com/jeaye/orchestra/blob/master/test/cljc/orchestra/core_test.cljc#L47 as well as doc string support here: https://github.com/jeaye/orchestra/blob/master/test/cljc/orchestra/core_test.cljc#L72

Destructuring works, docs, meta maps. It should support everything `defn` does, since it uses the same specs to parse `defn-spec` as Clojure uses to parse `defn`.

**Comment by jeaye** [comment]
@didibus I have added docs and released `2017.11.12-1`. Feedback would be much appreciated! The docs are here: https://github.com/jeaye/orchestra#defn-spec

**Comment by sooheon** [comment]
@jeaye Now that this has been released for a while, do you have any experience getting Cursive to play nice with recognizing the syntax?

**Comment by jeaye** [comment]
@sooheon Nope, sorry! I work in Vim and the rest of my team is in Emacs. In Vim, for example, any form starting with `defn.*`, I think, gets indentation accordingly. If you do figure something out which Cursive requires, let me know and we can add it to the Orchestra readme. :slightly_smiling_face:

**Comment by sooheon** [comment]
Thanks, I think this is just a matter of internal support in Cursive.
