### ISSUE TITLE
Speccing higher-order functions

### ISSUE THREAD

**Issue by l3nz** [jeaye/orchestra#13]
I am trying to spec a higher-order function:

```
(defn expect-integer []
  (fn [i]
    (inc i)))

(s/fdef
  expect-integer
  :ret (s/fspec :args (s/cat :i int?)
                :ret int?))

(orchestra/instrument)
```

But if I run it:

```
((expect-integer) 1)
=> 2
((expect-integer) "a")
ClassCastException java.lang.String cannot be cast to java.lang.Number  clojure.lang.Numbers.inc (Numbers.java:112)
```

So the spec is not run. Is there a way to do it?

**Comment by l3nz** [comment]
I have a feeling that this might be added in a way similar to `defn-spec`, maybe having a `fn-spec`  macro, that will do the definition and instrument the function if the namespace requires it.

**Comment by jeaye** [comment]
Hi @l3nz. Thanks fo making the issue; let's see if we can get this figured out.

Your code currently only specs the return value of `expect-integer`. That's it, just what's returned. What you do with it after it's been returned is entirely unspec'd, which is why your second call isn't instrumented. So, using `fspec` on a returned function, with my understanding, is no different than just using `ifn?`, since you're not calling the fn in any place where that spec is still available. Your code has the same effect as this:

```clojure
(defn expect-integer []
  (fn [i]
    (inc i)))

(s/fdef
  expect-integer
  :ret ifn?)
```

> maybe having a fn-spec macro, that will do the definition and instrument the function if the namespace requires it.

I see where you're coming from with this. There are, however, a couple of issues with the approach, when I first consider them. Let me know if I'm misunderstanding something.

Firstly, the `fn-spec` (or `defn-spec`) macro will always redefine whichever name it has, or define a new one if it's gensymed, which means that the var for that fn will be new/updated, which finally means that instrumenting will *need* to be done again. Always. Unfortunately, doing that instrumenting automatically sounds like an issue to me, since Orchestra doesn't silently or automatically instrument anything anywhere else; instrumentation is always opt-in and explicit. Similarly, `defn-spec` just does a `defn` and an `s/def`; no instrumentation is enabled until the dev says so. In terms of performance, this also sounds rough, since every call to `expect-int`, in this case, would re-define, re-spec, and re-instrument the returned fn.

So, what do I suggest you do instead? Name your spec'd functions and define them at top-level. Keep your anonymous functions short and mainly composed of calls to spec'd functions. In this case:

```clojure
(defn-spec my-inc integer? [i integer?]
  (inc i))

(defn-spec expect-integer fn? []
  my-inc)

((expect-integer) 2) => 3
((expect-integer) 2.0) =>
clojure.lang.ExceptionInfo: Call to #'user/my-inc did not conform to spec:
                            In: [0] val: 2.0 fails at: [:args :i] predicate: integer?
                            :clojure.spec.alpha/spec  #object[clojure.spec.alpha$regex_spec_impl$reify__1200 0x53951a96 "clojure.spec.alpha$reg
ex_spec_impl$reify__1200@53951a96"]
                            :clojure.spec.alpha/value  (2.0)
                            :clojure.spec.alpha/args  (2.0)
                            :clojure.spec.alpha/failure  :instrument
                            :orchestra.spec.test/caller  {:file "form-init1741622501070430668.clj", :line 1, :var-scope user/eval39656}
```

If you see a different way this can be handled which isn't affected by those points, do let me know. I certainly could've missed something. Thanks again.

**Comment by darkleaf** [comment]
Hi!

I want rebind some my functions for testing. Maybe my tests will be runs at parallel in different threads.
And I want to use instrument wrapper: 

```
(s/fdef my-fn
            :ret #{:ok :error})
    
(defn ^:dynamic my-fn []
   (if (some-logic) :ok :error))

(defn other-fn []
  (my-fn)
  (some-another-logic))

(t/deftest other-function
  (let [my-fn-mock (constantly :wrong) ;; will fail with spec error
          my-fn-mock (orchestra/wrap-spec-check my-fn-mock `my-fn)] 
     (binding [my-fn my-fn-mock]
        (t/is (some-check? (other-fn))))))
```

`orchestra/wrap-spec-chec` is like `orchestra.spec.test/instrument-1`.

My suggestion requires a deep refactoring in `orchestra.spec.test`.

@jeaye what you think about `wrap-spec-check`?
