### ISSUE TITLE
Update for alpha spec?

### ISSUE THREAD

**Issue by danielcompton** [jeaye/orchestra#2]
Now that alpha spec is out, this library could be migrated to use its `clojure.spec.alpha` too. One thing to note is that `clojure.spec` has a different registry to `clojure.spec.alpha`, so spec registered in one registry can't be checked by code using the other spec version.

(Not saying you have to do this, I might get to it shortly, just leaving this issue as a marker).

**Comment by jeaye** [comment]
Thanks for opening this and pointing out the important caveat of the change. I think the way I'd approach this is to try something like this:

```clojure
(def registry (try
                (require [clojure.spec :as s])
                (catch Throwable _
                  (require [clojure.spec.alpha :as s]))
                (finally
                  (s/registry))))
```

If you'd like to try this out, I'd be happy to merge. If not, it's certainly something I can do. If this ends up being a hassle, I'd prefer to just jump into `clojure.spec.alpha`. Since we're working with alpha software here, there's not much reason to stay on any specific version. People can upgrade Orchestra when they upgrade Clojure.

**Comment by danielcompton** [comment]
I think its probably safer to just switch straight to `clojure.spec.alpha`. There's already going to be quite a bit of confusion about which specs are defined in which registries (for any libraries which define specs but haven't been updated), so I think it's probably better to rip the bandaid off.
