### ISSUE TITLE
How to instrument only a specific namespace

### ISSUE THREAD

**Issue by l3nz** [jeaye/orchestra#29]
Would you consider adding an `instrument` call that does instrumentation only on a specific namespace?

The problem being that I would like to terminate each namespace with a call to instrument, so that it's always instrumented if Orchestra is available, but as @martinklepsch says, it would be surprising if it turns on just everywhere.

(Context: https://github.com/l3nz/cli-matic/issues/48 )

**Comment by jeaye** [comment]
Hey there. Thanks for the request. This is a possibility, but I'm super hesitant to move Orchestra further away from core.spec, since keeping up with upstream changes is already a hassle. If there's some more demand for this, we could put it in, but I think we should all be pushing to get this into core.spec instead, which will then propagate it into Orchestra.

In the meantime, check out `instrument-1`, which instruments a single var. You could pretty reasonably iterate the vars you want to instrument them that way!

**Comment by l3nz** [comment]
Yep, makes sense.  😄
