### ISSUE TITLE
Improve a bit the output of unstrument

### ISSUE THREAD

**Issue by arichiardi** [jeaye/orchestra#33]
Hi @jeaye, thanks for this wonderful library - we use it everywhere :smile: 

I am trying to print the output of `orchestra/unstrument` for debugging purproses and I see:

```
eval [(quote laputa.scrutinize-fn.scrutinize)]
```

Where that is my namespace :smile: 

It is minor but shouldn't that print the namespace only?

Using the latest deployed version on Clojars at the moment.

Thanks a lot!

**Comment by jeaye** [comment]
Hey there, @arichiardi! Thanks for the report. This appears to be the same issue as #32, just applied to a different fn. I'm not sure what's going on there, or why Orchestra has this problem and Clojure doesn't (since Orchestra is just a hard fork).

I will, however, make sure this gets fixed in the next release.

**Comment by arichiardi** [comment]
Thanks a lot! Should I close this one in favor of #32?

**Comment by jeaye** [comment]
@arichiardi This has been fixed and will be in the release I cut tonight. Thanks for reporting!
