### ISSUE TITLE
package for npm

### ISSUE THREAD

**Issue by jerger** [jeaye/orchestra#49]
Hi,

we try to integrate orchestra in a node-cli-tool (https://github.com/yogthos/mastodon-bot/pull/48). For make installation easy for our users we would prefer orchestra being integrated as a npm dependency.

What do you think about packaging for npm?

Best Regards

**Comment by jeaye** [comment]
Hm, I don't fully understand why Orchestra would need to be on NPM, or how it could be. In order to put it on NPM, I'd need to compile it to JS first, but then Orchestra would be no use!

The important parts of Orchestra are implemented as macros and they must be compiled by Clojure/Script. This is because `instrument` is a macro.

I also saw, in that ticket you linked, that you mentioned Orchestra wasn't working properly. Please check the latest `development-SNAPSHOT` version, in which Orchestra has been rewritten. It should work better for you.

**Comment by jerger** [comment]
Yes, I agree. 

In meantime I found out how to integrate (even the non macro ones) directly. Shadow-cljs puts all of them in the compiled js if choosing the aprop. optimization :-)

**Comment by jeaye** [comment]
Oh, that's great. Happy hacking. :)
