### ISSUE TITLE
ClojureScript support?

### ISSUE THREAD

**Issue by vikeri** [jeaye/orchestra#5]
Is there anything limiting this from being supported in ClojureScript as well?

**Comment by jeaye** [comment]
@vikeri In theory, no. In practice, I have a `cljs` branch where I've tried to get things working and ClojureScript was giving me one hell of a time. This is primarily due to the macros used and the fact that `cljs.spec.alpha` is an entirely different codebase from `spec.alpha`. Ideally, Orchestra would unify them, since maintaining two almost identical codebases is just silly.

If you'd like to pick up on the `cljs` branch, or integrate your own (if you can do it more cleanly that I did), I'd be happy to merge. I'm also working on a CLJS project which would greatly benefit from Orchestra.

Thanks!

**Comment by jeaye** [comment]
This is now live; @vikeri @jiangts let me know if you have any problems with it!

**Comment by vikeri** [comment]
Tried it out and it works great! Surprisingly few return spec errors though, only 3 out of 209 specced functions.

**Comment by jeaye** [comment]
Sounds like some pretty successful spec writing. Nice work!

**Comment by vikeri** [comment]
We have generative tests running for most of them, and they usually catch these kinds of errors, so that might explain it.
